//
// Generated file, do not edit! Created by opp_msgtool 6.3 from messages.msg.
//

#ifndef __MESSAGES_M_H
#define __MESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SubtaskMsg;
class SubtaskResultMsg;
class GossipMsg;
/**
 * Class generated from <tt>messages.msg:12</tt> by opp_msgtool.
 * <pre>
 * // SubtaskMsg: Sent from initiator to target client via Chord routing.
 * // Contains the sub-array of elements for which the target must find the max.
 * message SubtaskMsg
 * {
 *     int subtaskId;          // Unique subtask identifier
 *     int initiatorId;        // Client that originated this task
 *     int targetClientId;     // Destination client (subtaskId % N)
 *     int sourceClientId;     // Last forwarding client (for routing)
 *     int elements[];         // Dynamic array of elements in this subtask
 *     int hopCount = 0;       // Number of hops taken so far
 * }
 * </pre>
 */
class SubtaskMsg : public ::omnetpp::cMessage
{
  protected:
    int subtaskId = 0;
    int initiatorId = 0;
    int targetClientId = 0;
    int sourceClientId = 0;
    int *elements = nullptr;
    size_t elements_arraysize = 0;
    int hopCount = 0;

  private:
    void copy(const SubtaskMsg& other);

  protected:
    bool operator==(const SubtaskMsg&) = delete;

  public:
    SubtaskMsg(const char *name=nullptr, short kind=0);
    SubtaskMsg(const SubtaskMsg& other);
    virtual ~SubtaskMsg();
    SubtaskMsg& operator=(const SubtaskMsg& other);
    virtual SubtaskMsg *dup() const override {return new SubtaskMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSubtaskId() const;
    virtual void setSubtaskId(int subtaskId);

    virtual int getInitiatorId() const;
    virtual void setInitiatorId(int initiatorId);

    virtual int getTargetClientId() const;
    virtual void setTargetClientId(int targetClientId);

    virtual int getSourceClientId() const;
    virtual void setSourceClientId(int sourceClientId);

    virtual void setElementsArraySize(size_t size);
    virtual size_t getElementsArraySize() const;
    virtual int getElements(size_t k) const;
    virtual void setElements(size_t k, int elements);
    virtual void insertElements(size_t k, int elements);
    [[deprecated]] void insertElements(int elements) {appendElements(elements);}
    virtual void appendElements(int elements);
    virtual void eraseElements(size_t k);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SubtaskMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SubtaskMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>messages.msg:24</tt> by opp_msgtool.
 * <pre>
 * // SubtaskResultMsg: Sent from the processing client back to the initiator.
 * // Contains the maximum value found in the subtask's sub-array.
 * message SubtaskResultMsg
 * {
 *     int subtaskId;          // Corresponding subtask ID
 *     int initiatorId;        // Original initiator (for identification)
 *     int targetClientId;     // Destination (= initiatorId, routed back)
 *     int sourceClientId;     // Last forwarding client
 *     int maxValue;           // Computed maximum of the sub-array
 *     int hopCount = 0;       // Number of hops taken so far
 * }
 * </pre>
 */
class SubtaskResultMsg : public ::omnetpp::cMessage
{
  protected:
    int subtaskId = 0;
    int initiatorId = 0;
    int targetClientId = 0;
    int sourceClientId = 0;
    int maxValue = 0;
    int hopCount = 0;

  private:
    void copy(const SubtaskResultMsg& other);

  protected:
    bool operator==(const SubtaskResultMsg&) = delete;

  public:
    SubtaskResultMsg(const char *name=nullptr, short kind=0);
    SubtaskResultMsg(const SubtaskResultMsg& other);
    virtual ~SubtaskResultMsg();
    SubtaskResultMsg& operator=(const SubtaskResultMsg& other);
    virtual SubtaskResultMsg *dup() const override {return new SubtaskResultMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSubtaskId() const;
    virtual void setSubtaskId(int subtaskId);

    virtual int getInitiatorId() const;
    virtual void setInitiatorId(int initiatorId);

    virtual int getTargetClientId() const;
    virtual void setTargetClientId(int targetClientId);

    virtual int getSourceClientId() const;
    virtual void setSourceClientId(int sourceClientId);

    virtual int getMaxValue() const;
    virtual void setMaxValue(int maxValue);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SubtaskResultMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SubtaskResultMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>messages.msg:36</tt> by opp_msgtool.
 * <pre>
 * // GossipMsg: Broadcast after a client completes its entire task.
 * // Format: <timestamp>:<IP>:<ClientID>
 * message GossipMsg
 * {
 *     int originClientId;     // Client that generated this gossip
 *     string timestamp;       // Simulation time when gossip was generated
 *     string ipAddress;       // Simulated IP of the origin client
 *     string msgContent;      // Full gossip string: "timestamp:IP:clientId"
 *     int senderClientId;     // Last hop sender (to avoid reverse forwarding)
 *     string msgHash;         // Hash of msgContent for deduplication (ML)
 * }
 * </pre>
 */
class GossipMsg : public ::omnetpp::cMessage
{
  protected:
    int originClientId = 0;
    omnetpp::opp_string timestamp;
    omnetpp::opp_string ipAddress;
    omnetpp::opp_string msgContent;
    int senderClientId = 0;
    omnetpp::opp_string msgHash;

  private:
    void copy(const GossipMsg& other);

  protected:
    bool operator==(const GossipMsg&) = delete;

  public:
    GossipMsg(const char *name=nullptr, short kind=0);
    GossipMsg(const GossipMsg& other);
    virtual ~GossipMsg();
    GossipMsg& operator=(const GossipMsg& other);
    virtual GossipMsg *dup() const override {return new GossipMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getOriginClientId() const;
    virtual void setOriginClientId(int originClientId);

    virtual const char * getTimestamp() const;
    virtual void setTimestamp(const char * timestamp);

    virtual const char * getIpAddress() const;
    virtual void setIpAddress(const char * ipAddress);

    virtual const char * getMsgContent() const;
    virtual void setMsgContent(const char * msgContent);

    virtual int getSenderClientId() const;
    virtual void setSenderClientId(int senderClientId);

    virtual const char * getMsgHash() const;
    virtual void setMsgHash(const char * msgHash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GossipMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GossipMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SubtaskMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<SubtaskMsg*>(ptr.get<cObject>()); }
template<> inline SubtaskResultMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<SubtaskResultMsg*>(ptr.get<cObject>()); }
template<> inline GossipMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<GossipMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGES_M_H

